from typing import Protocol, Any
from sklearn.base import BaseEstimator

class ModelVersioningProtocol(Protocol):
    def create_and_log_model_artifact_to_run(self, model: BaseEstimator, alias: str, metric: float) -> None:
        ...
    def create_and_log_preprocessor_artifact_to_run(self, preprocessor: BaseEstimator, alias: str) -> None:
        ...
    def stream_load_from_alias(self, artifact_name: str, alias: str) -> Any:
        ...
    def promote_artifact(self, artifact_name: str, from_alias: str, to_alias: str) -> None:
        ...